name: Heroku Build + Deploy

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v2
            -   name: Setup node
                uses: actions/setup-node@v2
                with:
                    node-version: 15
            -   name: Install dependencies and build app
                run: |
                    yarn install --frozen-lockfile
                    yarn run build
            -   name: Test fs on action
                run: ls
